# Problem Statement : 

# Fake News Classification with The Help Of Natural Language Processing Technique. 
Fake news detection is a hot topic in the field of natural language processing.
We consume news through several mediums throughout the day in our daily routine, but sometimes it becomes difficult to decide which one is fake and which one is authentic. Our job is to create a model which predicts whether a given news is real or fake.

# Required Libraries

In [1]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Data Gathering

In [3]:
df = pd.read_csv("WELFake_Dataset.csv")
df.head()

Unnamed: 0                                              title   
0           0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...  \
1           1                                                NaN   
2           2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3           3  Bobby Jindal, raised Hindu, uses story of Chri...   
4           4  SATAN 2: Russia unvelis an image of its terrif...   

                                                text  label  
0  No comment is expected from Barack Obama Membe...      1  
1     Did they post their votes for Hillary already?      1  
2   Now, most of the demonstrators gathered last ...      1  
3  A dozen politically active pastors came here f...      0  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...      1

# 2. Data Analysis

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72134 entries, 0 to 72133
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  72134 non-null  int64 
 1   title       71576 non-null  object
 2   text        72095 non-null  object
 3   label       72134 non-null  int64 
dtypes: int64(2), object(2)
memory usage: 2.2+ MB


In [5]:
df['label'].value_counts()

label
1    37106
0    35028
Name: count, dtype: int64

In [6]:
df.shape

(72134, 4)

In [7]:
df.isna().sum()

Unnamed: 0      0
title         558
text           39
label           0
dtype: int64

In [8]:
df = df.dropna() #Handled Missing values by droping those rows

In [9]:
df.isna().sum()

Unnamed: 0    0
title         0
text          0
label         0
dtype: int64

In [10]:
df.shape

(71537, 4)

In [11]:
df.reset_index(inplace=True)
df.head()

index  Unnamed: 0                                              title   
0      0           0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...  \
1      2           2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
2      3           3  Bobby Jindal, raised Hindu, uses story of Chri...   
3      4           4  SATAN 2: Russia unvelis an image of its terrif...   
4      5           5  About Time! Christian Group Sues Amazon and SP...   

                                                text  label  
0  No comment is expected from Barack Obama Membe...      1  
1   Now, most of the demonstrators gathered last ...      1  
2  A dozen politically active pastors came here f...      0  
3  The RS-28 Sarmat missile, dubbed Satan 2, will...      1  
4  All we can say on this one is it s about time ...      1

In [12]:
df['title'][0]

'LAW ENFORCEMENT ON HIGH ALERT Following Threats Against Cops And Whites On 9-11By #BlackLivesMatter And #FYF911 Terrorists [VIDEO]'

In [13]:
df = df.drop(['index','Unnamed: 0'],axis = 1)
df.head()

title   
0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...  \
1  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
2  Bobby Jindal, raised Hindu, uses story of Chri...   
3  SATAN 2: Russia unvelis an image of its terrif...   
4  About Time! Christian Group Sues Amazon and SP...   

                                                text  label  
0  No comment is expected from Barack Obama Membe...      1  
1   Now, most of the demonstrators gathered last ...      1  
2  A dozen politically active pastors came here f...      0  
3  The RS-28 Sarmat missile, dubbed Satan 2, will...      1  
4  All we can say on this one is it s about time ...      1

# 3. Data Preprocessing

## 1.Tokenization

In [21]:
sample_data = 'The quick brown fox jumps over the lazy dog'
sample_data = sample_data.split()
sample_data

['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']

## 2. Make Lowercase

In [22]:
sample_data = [data.lower() for data in sample_data]
sample_data

['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']

## 3. Remove Stopwords

In [23]:
stopwords = stopwords.words('english')
print(stopwords[0:10])
print(len(stopwords))

AttributeError: 'list' object has no attribute 'words'

In [19]:
sample_data = [data for data in sample_data if data not in stopwords]
print(sample_data)
len(sample_data)

NameError: name 'sample_data' is not defined

## 4. Stemming

In [17]:
ps = PorterStemmer()
sample_data_stemming = [ps.stem(data) for data in sample_data]
print(sample_data_stemming)

NameError: name 'sample_data' is not defined

## 5. Lemmatization

In [15]:
df['content'] = df['title'] + ' ' + df['text']
df.head(10)

title   
0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...  \
1  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
2  Bobby Jindal, raised Hindu, uses story of Chri...   
3  SATAN 2: Russia unvelis an image of its terrif...   
4  About Time! Christian Group Sues Amazon and SP...   
5  DR BEN CARSON TARGETED BY THE IRS: “I never ha...   
6  HOUSE INTEL CHAIR On Trump-Russia Fake Story: ...   
7  Sports Bar Owner Bans NFL Games…Will Show Only...   
8  Latest Pipeline Leak Underscores Dangers Of Da...   
9   GOP Senator Just Smacked Down The Most Puncha...   

                                                text  label   
0  No comment is expected from Barack Obama Membe...      1  \
1   Now, most of the demonstrators gathered last ...      1   
2  A dozen politically active pastors came here f...      0   
3  The RS-28 Sarmat missile, dubbed Satan 2, will...      1   
4  All we can say on this one is it s about time ...      1   
5  DR. BEN CARSON TELLS THE STORY OF WHAT HAPPENE...      1   
6                                                         1   
7  The owner of the Ringling Bar, located south o...      1   
8  FILE – In this Sept. 15, 2005 file photo, the ...      1   
9  The most punchable Alt-Right Nazi on the inter...      1   

                                             content  
0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...  
1  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...  
2  Bobby Jindal, raised Hindu, uses story of Chri...  
3  SATAN 2: Russia unvelis an image of its terrif...  
4  About Time! Christian Group Sues Amazon and SP...  
5  DR BEN CARSON TARGETED BY THE IRS: “I never ha...  
6  HOUSE INTEL CHAIR On Trump-Russia Fake Story: ...  
7  Sports Bar Owner Bans NFL Games…Will Show Only...  
8  Latest Pipeline Leak Underscores Dangers Of Da...  
9   GOP Senator Just Smacked Down The Most Puncha...

In [30]:
lm = WordNetLemmatizer()
sample_data_lemma = [lm.lemmatize(data) for data in sample_data]
print(sample_data_lemma)

['quick', 'brown', 'fox', 'jump', 'lazy', 'dog']


In [16]:
lm = WordNetLemmatizer()
corpus = []
for i in range (len(df)):
    review = re.sub('^a-zA-Z0-9',' ', df['content'][i])
    review = review.lower()
    review = review.split()
    review = [lm.lemmatize(x) for x in review if x not in stopwords]
    review = " ".join(review)
    corpus.append(review)

TypeError: argument of type 'LazyCorpusLoader' is not iterable

In [35]:
len(corpus)

18285

In [36]:
df['title'][0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It'

In [37]:
corpus[0]

'house dem aide: didn’t even see comey’s letter jason chaffetz tweeted'

# 4. Vectorization (Convert Text data into the Vector)

In [38]:
tf = TfidfVectorizer()
x = tf.fit_transform(corpus).toarray()
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [39]:
y = df['label']
y.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

## Data splitting into the train and test

In [46]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3, random_state = 10, stratify = y )

In [41]:
len(x_train),len(y_train)

(12799, 12799)

In [42]:
len(x_test), len(y_test)

(5486, 5486)

# 5. Model Building

In [43]:
rf = RandomForestClassifier()
rf.fit(x_train, y_train)

RandomForestClassifier()

# 6. Model Evaluation

In [47]:
y_pred = rf.predict(x_test)
accuracy_score_ = accuracy_score(y_test,y_pred) 
accuracy_score_

0.9385709077652206

In [64]:
class Evaluation:
    
    def __init__(self,model,x_train,x_test,y_train,y_test):
        self.model = model
        self.x_train = x_train
        self.x_test = x_test
        self.y_train = y_train
        self.y_test = y_test
        
    def train_evaluation(self):
        y_pred_train = self.model.predict(self.x_train)
        
        acc_scr_train = accuracy_score(self.y_train,y_pred_train)
        print("Accuracy Score On Training Data Set :",acc_scr_train)
        print()
        
        con_mat_train = confusion_matrix(self.y_train,y_pred_train)
        print("Confusion Matrix On Training Data Set :\n",con_mat_train)
        print()
        
        class_rep_train = classification_report(self.y_train,y_pred_train)
        print("Classification Report On Training Data Set :\n",class_rep_train)
        
        
    def test_evaluation(self):
        y_pred_test = self.model.predict(self.x_test)
        
        acc_scr_test = accuracy_score(self.y_test,y_pred_test)
        print("Accuracy Score On Testing Data Set :",acc_scr_train)
        print()
        
        con_mat_test = confusion_matrix(self.y_test,y_pred_test)
        print("Confusion Matrix On Testing Data Set :\n",con_mat_train)
        print()
        
        class_rep_test = classification_report(self.y_test,y_pred_test)
        print("Classification Report On Testing Data Set :\n",class_rep_train)
        
        

In [51]:
#Checking the accuracy on training dataset

Evaluation(rf,x_train, x_test, y_train, y_test).train_evaluation()


Accuracy Score On Training Data Set : 1.0

Confusion Matrix On Training Data Set :
 [[7252    0]
 [   0 5547]]

Classification Report On Training Data Set :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      7252
           1       1.00      1.00      1.00      5547

    accuracy                           1.00     12799
   macro avg       1.00      1.00      1.00     12799
weighted avg       1.00      1.00      1.00     12799



In [54]:
#Checking the accuracy on testing dataset
Evaluation(rf,x_train, x_test, y_train, y_test).test_evaluation()

Accuracy Score On Testing Data Set : 0.9385709077652206

Confusion Matrix On Testing Data Set :
 [[2825  284]
 [  53 2324]]

Classification Report On Testing Data Set :
               precision    recall  f1-score   support

           0       0.98      0.91      0.94      3109
           1       0.89      0.98      0.93      2377

    accuracy                           0.94      5486
   macro avg       0.94      0.94      0.94      5486
weighted avg       0.94      0.94      0.94      5486



# Prediction Pipeline

In [55]:
class Preprocessing:
    
    def __init__(self,data):
        self.data = data
        
    def text_preprocessing_user(self):
        lm = WordNetLemmatizer()
        pred_data = [self.data]    
        preprocess_data = []
        for data in pred_data:
            review = re.sub('^a-zA-Z0-9',' ', data)
            review = review.lower()
            review = review.split()
            review = [lm.lemmatize(x) for x in review if x not in stopwords]
            review = " ".join(review)
            preprocess_data.append(review)
        return preprocess_data    

In [57]:
df['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [58]:
data = 'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'
Preprocessing(data).text_preprocessing_user()

['flynn: hillary clinton, big woman campus - breitbart']

In [65]:
class Prediction:
    
    def __init__(self,pred_data, model):
        self.pred_data = pred_data
        self.model = model
        
    def prediction_model(self):
        preprocess_data = Preprocessing(self.pred_data).text_preprocessing_user()
        data = tf.transform(preprocess_data)
        prediction = self.model.predict(data)
        
        if prediction [0] == 0 :
            return "The News Is Fake"
        
        else:
            return "The News Is Real"
        

In [61]:
data = 'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'
Prediction(data,rf).prediction_model()

'The News Is Fake'

In [62]:
df['title'][3]

'15 Civilians Killed In Single US Airstrike Have Been Identified'

In [66]:
user_data = '15 Civilians Killed In Single US Airstrike Have Been Identified' 
Prediction(user_data,rf).prediction_model()

'The News Is Real'